name=estero-gt-guided-gwc-film
restore_ckpt=None
logdir=./checkpoints/$name
batch_size=6
train_datasets=sceneflow
lr=0.0002
num_steps=20000

export CUDA_VISIBLE_DEVICES=3

python train_stereo.py \
    --name $name \
    --logdir $logdir \
    --batch_size $batch_size \
    --train_datasets $train_datasets \
    --lr $lr \
    --num_steps $num_steps \
    --edge_source gt --edge_model None \
    --edge_guided_gwc --edge_gwc_fusion_mode film



# --edge_source gt --edge_model None                # Edge source: 'gt' uses externally loaded GT edges (e.g., pre-generated by gtedge.py)
# --edge_context_fusion --edge_fusion_mode film       # Fuse Edge into Context
# --edge_guided_upsample --edge_upsample_fusion_mode film  # Edge-guided upsampling
# --edge_guided_disp_head --edge_disp_fusion_mode film     # Edge-guided Disp Head
# --edge_guided_cost_agg --edge_cost_agg_fusion_mode film # Inject Edge into Cost Agg (Hourglass) to optimize init_disp
# --edge_guided_gwc --edge_gwc_fusion_mode film         # Inject Edge into GWC corr_feature_att for boundary-aware initial cost
# --edge_motion_encoder --edge_motion_fusion_mode film   # Inject Edge into Motion Encoder for boundary-aware motion features
# --edge_guided_refinement --edge_refinement_fusion_mode film  # Edge-guided disparity refinement post-processing for boundary sharpening
# --boundary_only_refinement --edge_refinement_fusion_mode film  # Refinement only in boundary regions, not applied in flat areas
